// Procedural battle audio: layered casts, real impacts, and independent music/SFX buses.
let audioCtx=null,audioMaster=null,audioNoise=null,audioMusicBus=null,lastLowHpSound=0;
const AUDIO_KEY='ochames2-audio-v2';
let audioSettings={effects:.75,music:.48,mute:false};
try{const s=JSON.parse(localStorage.getItem(AUDIO_KEY)||'null');if(s&&typeof s==='object')for(const k of ['effects','music'])if(Number.isFinite(Number(s[k])))audioSettings[k]=Math.max(0,Math.min(1,Number(s[k])));if(s)audioSettings.mute=!!s.mute;}catch(e){}
let audioLimiter=null,activeCastSide=null,lastSignature=null;
function persistAudio(){try{localStorage.setItem(AUDIO_KEY,JSON.stringify(audioSettings));}catch(e){}applyAudioVolume();}
function applyAudioVolume(){if(!audioCtx)return;if(audioMaster)audioMaster.gain.setTargetAtTime(audioSettings.mute?0:audioSettings.effects*.48,audioCtx.currentTime,.045);if(audioMusicBus)audioMusicBus.gain.setTargetAtTime(audioSettings.mute?0:audioSettings.music*.62,audioCtx.currentTime,.16);}
function initAudio(){try{if(!audioCtx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audioCtx=new C();audioLimiter=audioCtx.createDynamicsCompressor();audioLimiter.threshold.value=-18;audioLimiter.knee.value=12;audioLimiter.ratio.value=10;audioLimiter.attack.value=.003;audioLimiter.release.value=.23;audioLimiter.connect(audioCtx.destination);audioMaster=audioCtx.createGain();audioMaster.connect(audioLimiter);audioMusicBus=audioCtx.createGain();audioMusicBus.connect(audioLimiter);const buffer=audioCtx.createBuffer(1,Math.ceil(audioCtx.sampleRate*.6),audioCtx.sampleRate);const arr=buffer.getChannelData(0);for(let i=0;i<arr.length;i++)arr[i]=Math.random()*2-1;audioNoise=buffer;applyAudioVolume();}if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});return audioCtx;}catch(e){return null;}}
window.addEventListener('pointerdown',initAudio,{passive:true});window.addEventListener('keydown',initAudio);
function playTone(freq,type,duration,gain=.2,slideToFreq=null,options={}){const ctx=initAudio();if(!ctx)return;try{const t=ctx.currentTime+Math.max(0,Number(options.delay)||0),d=Math.min(2,Math.max(.025,duration)),osc=ctx.createOscillator(),env=ctx.createGain(),target=options.music?audioMusicBus:audioMaster;osc.type=['sine','triangle','sawtooth','square'].includes(type)?type:'sine';osc.frequency.setValueAtTime(Math.max(25,freq),t);if(slideToFreq)osc.frequency.exponentialRampToValueAtTime(Math.max(25,slideToFreq),t+d);env.gain.setValueAtTime(.0001,t);env.gain.exponentialRampToValueAtTime(Math.max(.0001,Math.min(.38,gain)),t+.006);env.gain.exponentialRampToValueAtTime(.0001,t+d);osc.connect(env);if(options.pan!==undefined&&ctx.createStereoPanner){const pan=ctx.createStereoPanner();pan.pan.value=Math.max(-1,Math.min(1,options.pan));env.connect(pan).connect(target);osc.onended=()=>{osc.disconnect();env.disconnect();pan.disconnect();};}else{env.connect(target);osc.onended=()=>{osc.disconnect();env.disconnect();};}osc.start(t);osc.stop(t+d+.01);}catch(e){}}
function playNoise(duration,gain,options={}){const ctx=initAudio();if(!ctx||!audioNoise)return;try{const t=ctx.currentTime+Math.max(0,Number(options.delay)||0),d=Math.min(.55,Math.max(.025,duration)),src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),env=ctx.createGain();src.buffer=audioNoise;filter.type=options.filter||'lowpass';filter.frequency.setValueAtTime(Math.max(80,options.cutoff||1500),t);if(options.endCutoff)filter.frequency.exponentialRampToValueAtTime(Math.max(80,options.endCutoff),t+d);env.gain.setValueAtTime(.0001,t);env.gain.exponentialRampToValueAtTime(Math.max(.0001,Math.min(.35,gain)),t+.006);env.gain.exponentialRampToValueAtTime(.0001,t+d);src.connect(filter).connect(env);const target=options.music?audioMusicBus:audioMaster;if(options.pan!==undefined&&ctx.createStereoPanner){const pan=ctx.createStereoPanner();pan.pan.value=Math.max(-1,Math.min(1,options.pan));env.connect(pan).connect(target);src.onended=()=>{src.disconnect();filter.disconnect();env.disconnect();pan.disconnect();};}else{env.connect(target);src.onended=()=>{src.disconnect();filter.disconnect();env.disconnect();};}src.start(t);src.stop(t+d);}catch(e){}}
function playNotes(notes,type='triangle',spacing=.07,gain=.12){notes.forEach((f,i)=>playTone(f,type,.18,gain,null,{delay:i*spacing}));}
function pan(){if(activeCastSide===null)return 0;try{const mine=(isHost||isSpectator)?activeCastSide==='p1':activeCastSide==='p2';return mine?-.35:.35;}catch(e){return 0;}}
function signatureCast(name){const p=pan(),o={pan:p};lastSignature={name,at:Date.now(),pan:p};switch(name){
case '드레인펀치':playTone(71,'sine',.53,.27,33,o);playNoise(.24,.15,{filter:'highpass',cutoff:550,pan:p,delay:.12});playTone(190,'sawtooth',.22,.12,58,{pan:p,delay:.25});break;
case '오물폭탄':playTone(82,'sine',.85,.24,36,o);playNoise(.42,.18,{cutoff:640,endCutoff:160,pan:p,delay:.11});playTone(460,'sawtooth',.36,.10,102,{pan:p,delay:.21});break;
case '메테오 스트라이크':playNoise(.45,.13,{filter:'highpass',cutoff:650,endCutoff:1700,pan:p});playTone(145,'triangle',.83,.18,35,{pan:p,delay:.16});playTone(53,'sine',.55,.22,27,{pan:p,delay:.47});break;
case '화염방사':for(let i=0;i<4;i++)playNoise(.35,.12,{filter:'highpass',cutoff:950,endCutoff:3500,pan:p,delay:i*.23});playTone(175,'sawtooth',1.1,.13,85,o);break;
case '벽력일섬':playTone(52,'sine',.76,.27,35,o);playNoise(.25,.19,{filter:'highpass',cutoff:2100,pan:p,delay:.26});playTone(920,'sawtooth',.21,.13,125,{pan:p,delay:.39});break;
case '수능 가챠':playNotes([392,523,659,784], 'triangle',.13,.08);playNoise(.22,.07,{filter:'highpass',cutoff:1400,pan:p,delay:.33});break;
case '사이코 쇼크':playTone(410,'sine',.55,.15,980,o);playTone(710,'triangle',.32,.10,290,{pan:p,delay:.2});break;
case '롱레인지 찌르기':playNoise(.17,.14,{filter:'highpass',cutoff:2400,pan:p});playTone(730,'sawtooth',.23,.13,180,o);break;
default:playNoise(.14,.08,{filter:'highpass',cutoff:800,pan:p});playTone(290,'triangle',.16,.09,130,o);
}}
function signatureImpact(name,result='normal'){if(result==='miss')return SFX.dodge();const p=lastSignature?.name===name&&Date.now()-lastSignature.at<6500?lastSignature.pan:pan(),power=result==='crit'?1.3:result==='super'?1.17:result==='weak'?.62:1;const low=name==='메테오 스트라이크'?45:name==='드레인펀치'?58:name==='오물폭탄'?70:name==='화염방사'?90:65;playTone(low,'sine',.53,.26*power,28,{pan:p});playNoise(.25,.18*power,{cutoff:name==='오물폭탄'?650:1800,pan:p});playTone(name==='메테오 스트라이크'?130:260,'triangle',.2,.14*power,48,{pan:p,delay:.035});if(name==='드레인펀치')playNoise(.32,.10,{filter:'highpass',cutoff:2700,pan:p,delay:.08});if(name==='오물폭탄')for(let i=1;i<=3;i++)playNoise(.12,.045,{cutoff:460,pan:p,delay:i*.12});if(result==='crit')playTone(1200,'triangle',.13,.11,320,{pan:p,delay:.08});}
const signature=new Set(['드레인펀치','오물폭탄','메테오 스트라이크','화염방사','벽력일섬','수능 가챠','사이코 쇼크','롱레인지 찌르기']);
const SFX={
click:()=>playTone(680,'sine',.055,.07,920),lunge:()=>{playNoise(.13,.08,{filter:'highpass',cutoff:800});playTone(300,'triangle',.16,.1,110);},
hit:()=>signatureImpact('일반'),superHit:()=>signatureImpact('일반','super'),weakHit:()=>signatureImpact('일반','weak'),crit:()=>signatureImpact('일반','crit'),
protect:()=>{playTone(710,'sine',.26,.11,1450);playTone(1030,'triangle',.23,.08,520,{delay:.08});},rankUp:()=>playNotes([330,440,554,659]),rankDown:()=>playNotes([659,554,440,330],'sawtooth'),heal:()=>playNotes([523,659,784,1046],'sine'),
switchIn:()=>{playNoise(.16,.07,{filter:'highpass',cutoff:1400});playTone(260,'sine',.22,.12,760);},faint:()=>{playTone(330,'sawtooth',.48,.15,46);playTone(90,'sine',.5,.15,29,{delay:.1});},dodge:()=>{playNoise(.11,.11,{filter:'highpass',cutoff:2000});playTone(660,'sine',.12,.08,990);},
poison:()=>{playTone(480,'sawtooth',.2,.1,140);playNoise(.18,.1,{cutoff:700});},burn:()=>{playNoise(.24,.13,{filter:'highpass',cutoff:1400});playTone(150,'sawtooth',.25,.09,55);},paralyze:()=>{playNoise(.08,.14,{filter:'highpass',cutoff:4200});playTone(1900,'square',.04,.08,310);},
lowHp:()=>{if(Date.now()-lastLowHpSound<1350)return;lastLowHpSound=Date.now();playTone(85,'sine',.3,.24,40);playTone(74,'sine',.28,.2,36,{delay:.34});},victory:()=>playNotes([392,523,659,784,1046],'triangle',.11,.13),defeat:()=>playNotes([440,349,294,220],'sine',.17,.11),
drain:()=>signatureCast('드레인펀치'),bulkup:()=>{playTone(140,'sawtooth',.37,.12,280);SFX.rankUp();},sludge:()=>signatureCast('오물폭탄'),charm:()=>playNotes([880,660,520],'sine'),thunderbolt:()=>signatureCast('벽력일섬'),charge:()=>{playTone(170,'sine',.38,.14,900);playTone(480,'triangle',.26,.1,1300,{delay:.12});},
meteor:()=>signatureCast('메테오 스트라이크'),sandstorm:()=>playNoise(.44,.13,{filter:'bandpass',cutoff:1100,endCutoff:480}),flameStream:()=>signatureCast('화염방사'),psychic:()=>signatureCast('사이코 쇼크'),barrier:()=>SFX.protect(),chaos:()=>{playTone(650,'square',.12,.12,125);playNoise(.16,.1,{cutoff:1800});},timeLeap:()=>{playTone(210,'sine',.35,.15,1260);playNoise(.15,.07,{filter:'highpass',cutoff:2100,delay:.12});},airSlash:()=>{playNoise(.17,.12,{filter:'highpass',cutoff:1600});playTone(480,'triangle',.2,.12,930);},rewind:()=>playTone(970,'sawtooth',.42,.12,150),
gachaWin:()=>{playNotes([523,659,784,1046,1318,1568],'triangle',.075,.11);for(let i=0;i<6;i++)playTone(1200+i*95,'sine',.16,.045,700,{delay:i*.09});},gachaFail:()=>{playTone(320,'sawtooth',.2,.12,100);playTone(95,'sine',.34,.15,40,{delay:.16});},
skillCast:name=>{if(signature.has(name))signatureCast(name);else {const map={'피의 방패':'protect','벌크업':'bulkup','멘헤라 가드':'protect','기생독':'poison','보인고 매혹':'charm','충전':'charge','철벽 방어':'protect','스텔스 아머':'barrier','모래바람':'sandstorm','수능 가챠':'charge','화염 장벽':'protect','도깨비불':'burn','절대 방어':'protect','리플렉트 실드':'barrier','흑안개':'rewind','스플래시 매직':'chaos','타임 리프 스트라이크':'timeLeap','광기의 예언서':'chaos','익스트림 카오스':'chaos','페이스 조절':'airSlash','되감기':'rewind','빨리감기':'airSlash','오버차지':'charge','작용반작용':'airSlash'};const key=map[name];(SFX[key]||SFX.lunge)();}},
skillImpact:(name,result='normal')=>{if(signature.has(name))signatureImpact(name,result);else signatureImpact('일반',result);},killConfirm:()=>playNotes([659,880,1175,1568],'triangle',.07,.1),nikaBeat:()=>{for(let i=0;i<4;i++)playTone(75,'sine',.12,.2,44,{delay:i*.18});},clockTick:()=>{playTone(1300,'triangle',.05,.07,800);playTone(880,'triangle',.055,.06,520,{delay:.13});},clown:()=>playNotes([660,550,830,390],'triangle',.07,.06),meteorCrash:()=>playTone(47,'sine',.4,.14,29)
};
const BATTLE_TRACKS=[{bpm:132,bass:[55,44,65,49],lead:[440,523,659,523,392,523,659,784]},{bpm:148,bass:[62,49,55,73],lead:[494,587,740,587,554,740,880,740]},{bpm:122,bass:[65,52,58,44],lead:[523,659,784,1046,784,659,587,659]}];
const DANGER_TRACK={bpm:96,bass:[41,39,37,44],lead:[330,311,262,247,294,262,233,247]};
let battleMusicTimer=null,battleMusicSession=0;
function startBattleMusic(isActive,isLowHp){const session=++battleMusicSession;if(battleMusicTimer)clearTimeout(battleMusicTimer);const normal=BATTLE_TRACKS[Math.floor(Math.random()*BATTLE_TRACKS.length)];let step=0,lastDanger=null;function tick(){if(session!==battleMusicSession)return;if(!isActive()){battleMusicTimer=null;return;}if(document.hidden){battleMusicTimer=setTimeout(tick,250);return;}const danger=!!isLowHp();if(danger!==lastDanger){step=0;lastDanger=danger;}const track=danger?DANGER_TRACK:normal,b=step%16,bar=Math.floor(step/16)%4,base=track.bass[bar];if(b%4===0){playTone(110,'sine',.2,.13,34,{music:true});playNoise(.07,.035,{cutoff:300,music:true});}if(b===4||b===12)playNoise(.11,.05,{filter:'highpass',cutoff:1500,music:true});if(b%2===0)playTone(base,'triangle',.2,.07,base*.8,{music:true});if(b%4===0)playTone(track.lead[(bar*2+b/4)%8],danger?'sine':'triangle',.15,.045,null,{music:true});step++;battleMusicTimer=setTimeout(tick,60000/track.bpm/4);}tick();}
function installAudioUI(){const header=document.querySelector('.header-btns');if(!header||document.getElementById('sound-settings-btn'))return;const btn=document.createElement('button');btn.type='button';btn.id='sound-settings-btn';btn.textContent='🔊 사운드';btn.className='info-toggle-btn';header.append(btn);btn.onclick=()=>{let shade=document.getElementById('audio-settings-modal');if(shade){shade.remove();return;}shade=document.createElement('div');shade.id='audio-settings-modal';Object.assign(shade.style,{position:'fixed',inset:'0',zIndex:'400',background:'#050816db',display:'grid',placeItems:'center',padding:'15px'});const card=document.createElement('div');Object.assign(card.style,{width:'min(340px,100%)',background:'#17243a',color:'#fff',border:'1px solid #7dd3fc',borderRadius:'12px',padding:'18px'});const heading=document.createElement('h2');heading.textContent='🔊 사운드 설정';card.append(heading);for(const [key,label] of [['effects','효과음'],['music','배경음악']]){const row=document.createElement('label');row.style.display='block';row.style.margin='12px 0';row.textContent=label;const slider=document.createElement('input');slider.type='range';slider.min='0';slider.max='100';slider.value=String(Math.round(audioSettings[key]*100));slider.style.width='100%';slider.oninput=()=>{audioSettings[key]=Number(slider.value)/100;persistAudio();};row.append(slider);card.append(row);}const mute=document.createElement('label');mute.textContent='음소거 ';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=audioSettings.mute;checkbox.onchange=()=>{audioSettings.mute=checkbox.checked;persistAudio();};mute.append(checkbox);card.append(mute);const close=document.createElement('button');close.textContent='닫기';close.style.display='block';close.style.marginTop='14px';close.onclick=()=>shade.remove();card.append(close);shade.append(card);document.body.append(shade);};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installAudioUI,{once:true});else installAudioUI();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{if(typeof window.triggerSkillVisualAndAudio==='function'){const old=window.triggerSkillVisualAndAudio;window.triggerSkillVisualAndAudio=function(name,side,...args){activeCastSide=side;try{return old.call(this,name,side,...args);}finally{activeCastSide=null;}};}},{once:true});
