// Cosmetic skin finishers. Combat move ids and damage remain unchanged.
(() => {
'use strict';
const css=document.createElement('style');css.textContent=`
.finisher-extra{position:absolute;inset:0;width:100%;height:100%;z-index:54;pointer-events:none}
.stomp-leap .champion-art,.stomp-leap .sprite-label{opacity:0!important}
#battle-screen[data-park-stomp="yes"] .unified-skin-fx,#battle-screen[data-park-stomp="impact"] .unified-skin-fx,#battle-screen[data-park-stomp="yes"] .remote-skin-fx,#battle-screen[data-park-stomp="impact"] .remote-skin-fx,#battle-screen[data-park-stomp="yes"] .skin-cinematic,#battle-screen[data-park-stomp="impact"] .skin-cinematic{display:none!important}
#battle-screen[data-park-stomp="yes"] #fx-canvas{opacity:0}
.stomp-squashed{transition:scale .2s!important;transform-origin:50% 100%!important}
.battle-screen.finisher-shake{animation:finisherShake .76s ease-out!important}
@keyframes finisherShake{0%,100%{transform:translate(0)}12%{transform:translate(19px,-11px) rotate(1deg)}25%{transform:translate(-20px,12px) rotate(-1deg)}40%{transform:translate(17px,9px)}60%{transform:translate(-15px,-10px)}80%{transform:translate(7px,4px)}}
.fractured-screen{position:absolute;inset:0;z-index:36;width:100%;height:100%;pointer-events:none;animation:fracturePulse 1.4s ease-in-out infinite}
.fractured-screen path{fill:none;stroke:#e8f6ff;stroke-width:2.7;filter:drop-shadow(1px 2px 2px #111827) drop-shadow(0 0 4px #fff)}
@keyframes fracturePulse{50%{opacity:.78}}
.metal-plating{position:absolute;inset:0;z-index:3;pointer-events:none;border-radius:inherit;background:linear-gradient(115deg,transparent,#ffffff8a 46%,#4f6a8766 52%,transparent);mix-blend-mode:screen;animation:steelShine 2.6s ease-in-out infinite}
@keyframes steelShine{50%{opacity:.4}}
#battle-screen.sludge-wobble{isolation:isolate;filter:url(#sludge-melt-filter);animation:sludgeScreen 1.3s ease-in-out infinite}
@keyframes sludgeScreen{0%,100%{border-radius:12px}50%{border-radius:22px 7px 20px 8px}}
.sludge-liquid{position:absolute;inset:0;z-index:52;pointer-events:none;overflow:hidden;background:linear-gradient(180deg,#25102f6b,transparent 43%,#0b051b5c)}
.sludge-liquid::before{content:'';position:absolute;left:-4%;top:-32%;width:108%;height:69%;background:radial-gradient(ellipse 21px 90px at 8% 48%,#3f0d59ce 25%,transparent 82%),radial-gradient(ellipse 26px 106px at 19% 55%,#10061eea 20%,transparent 80%),radial-gradient(ellipse 24px 117px at 34% 42%,#821cacbd 28%,transparent 80%),radial-gradient(ellipse 24px 92px at 49% 54%,#18051edb 28%,transparent 82%),radial-gradient(ellipse 28px 130px at 63% 48%,#4b1177c9 25%,transparent 83%),radial-gradient(ellipse 23px 105px at 78% 51%,#12051cdb 28%,transparent 80%),radial-gradient(ellipse 25px 123px at 92% 50%,#7e22ceb9 25%,transparent 80%),linear-gradient(#0c031c88,#63218880 42%,transparent 75%);filter:drop-shadow(0 9px 17px #7e22ce);animation:sludgeDrip 1.7s ease-in-out infinite alternate}
.sludge-liquid::after{content:'';position:absolute;inset:0;background:repeating-radial-gradient(ellipse at 50% 115%,transparent 0 22px,#e9afff39 24px 27px,transparent 30px 47px);animation:sludgeCurrent 2s linear infinite}
@keyframes sludgeDrip{from{transform:translateY(-13%) scaleY(.8)}to{transform:translateY(46%) scaleY(1.3)}}
@keyframes sludgeCurrent{to{transform:translateY(-24px) scaleX(1.1)}}
.sludge-hit{position:absolute;z-index:56;width:34px;height:34px;border:5px solid #d99aff;border-radius:50%;box-shadow:0 0 22px #591470;pointer-events:none;animation:sludgeHit .48s ease-out both}
@keyframes sludgeHit{from{opacity:1;transform:translate(-50%,-50%) scale(.25)}to{opacity:0;transform:translate(-50%,-50%) scale(4.5)}}
.jackpot-wealth{position:absolute;inset:-25px;z-index:5;pointer-events:none;border-radius:50%;box-shadow:0 0 24px #facc15,0 0 45px #f59e0b,inset 0 0 17px #fef08a;animation:wealthGlow 1.6s ease-in-out infinite}
@keyframes wealthGlow{50%{filter:brightness(1.5);transform:scale(1.08)}}
.jackpot-wealth span{position:absolute;top:-42%;left:var(--x);font-size:var(--sz);animation:wealthFall var(--dur) linear infinite;animation-delay:var(--delay);filter:drop-shadow(0 0 6px #ffe27c)}
@keyframes wealthFall{to{transform:translate(var(--drift),235px) rotate(360deg)}}
@media(prefers-reduced-motion:reduce){#battle-screen.sludge-wobble{filter:none;animation:none}.sludge-liquid::before,.sludge-liquid::after,.battle-screen.finisher-shake,.fractured-screen,.jackpot-wealth,.jackpot-wealth span{animation:none!important}}
`;document.head.append(css);
const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width','0');svg.setAttribute('height','0');svg.setAttribute('aria-hidden','true');svg.innerHTML='<filter id="sludge-melt-filter" x="-5%" y="-5%" width="110%" height="110%"><feTurbulence type="fractalNoise" baseFrequency=".009 .023" numOctaves="2" seed="6" result="noise"><animate attributeName="baseFrequency" values=".009 .023;.018 .013;.009 .023" dur="1.6s" repeatCount="indefinite"/></feTurbulence><feDisplacementMap in="SourceGraphic" in2="noise" scale="18" xChannelSelector="R" yChannelSelector="G"/></filter>';document.body.append(svg);
const own=side=>(isHost||isSpectator)?side==='p1':side==='p2';
const sprite=me=>document.getElementById(me?'player-sprite':'enemy-sprite');
const mon=me=>me?myTeam?.lead:enemyTeam?.lead;
const has=(me,id,skin)=>mon(me)?.id===id&&sprite(me)?.dataset.skin===skin;
const saved=(id,skin)=>{try{const s=JSON.parse(localStorage.getItem('ochams-skins-v1')||'{}');return s.equipped?.[id]===skin&&s.unlocked?.includes(skin);}catch{return false;}};
const at=(el,field)=>{const a=field.getBoundingClientRect(),b=el.getBoundingClientRect();return{x:b.left-a.left+b.width/2,y:b.top-a.top+b.height/2};};
const mix=(a,b,t)=>a+(b-a)*t,ease=x=>1-(1-Math.max(0,Math.min(1,x)))**3;
const front=new Image();front.src='assets/skins/park-meteor.jpg';
let fxKey=0,token=0,drain=null,stomp=null,sludge=null,crackUntil=-1,crackBattle=-1,flatTarget=null,flatId=null,flatUntil=-1,flatBattle=-1,wobbleUntil=-1,wobbleBattle=-1;
const coins=[0,0],leaders=[null,null];let moneyBattle=-1;
function shake(){const f=document.getElementById('battle-screen');if(!f)return;f.classList.remove('finisher-shake');void f.offsetWidth;f.classList.add('finisher-shake');setTimeout(()=>f.classList.remove('finisher-shake'),800);}
function cracks(target){const f=document.getElementById('battle-screen');if(!f||!target)return;f.querySelector('.fractured-screen')?.remove();const p=at(target,f),x=p.x/f.clientWidth*1000,y=p.y/f.clientHeight*600;
const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 1000 600');s.setAttribute('preserveAspectRatio','none');s.setAttribute('class','fractured-screen');
for(const [ex,ey] of [[-50,-40],[300,-30],[760,-20],[1050,70],[1050,540],[760,650],[240,650],[-40,500]]){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',`M ${x} ${y} L ${mix(x,ex,.29)} ${mix(y,ey,.26)} L ${mix(x,ex,.56)+17} ${mix(y,ey,.54)-17} L ${ex} ${ey}`);s.append(p);}f.append(s);crackUntil=currentTurnNumber+1;crackBattle=battleGeneration;}
function appearance(){const f=document.getElementById('battle-screen');if(!f||!myTeam||!enemyTeam)return;
if(battleGeneration!==crackBattle||currentTurnNumber>crackUntil)f.querySelector('.fractured-screen')?.remove();
const melting=wobbleBattle===battleGeneration&&currentTurnNumber<=wobbleUntil;f.classList.toggle('sludge-wobble',melting);let liquid=f.querySelector('.sludge-liquid');if(melting&&!liquid){liquid=document.createElement('div');liquid.className='sludge-liquid';liquid.setAttribute('aria-hidden','true');f.append(liquid);}if(!melting)liquid?.remove();
if(moneyBattle!==battleGeneration){coins.fill(0);leaders.fill(null);moneyBattle=battleGeneration;}
for(const me of [true,false]){const e=sprite(me),m=mon(me);if(!e||!m)continue;const index=me?0:1;if(leaders[index]!==m.id){coins[index]=0;leaders[index]=m.id;}
const bae=has(me,'bae','bloodmoon'),park=has(me,'park','meteor'),flat=e===flatTarget&&flatBattle===battleGeneration&&currentTurnNumber<=flatUntil&&m.id===flatId&&!m.fainted;
const scale=bae?Math.min(2.45,1+Math.max(0,m.stages?.atk||0)*.48):1;e.classList.toggle('stomp-squashed',flat);e.style.transformOrigin=bae||flat?'50% 100%':'';e.style.scale=flat?`${scale} ${scale*.27}`:bae?String(scale):'';
const img=e.querySelector('img.champion-art');if(img)img.style.filter=park?`grayscale(${Math.min(1,(m.stages?.def||0)*.23)}) contrast(${1+Math.min(.6,(m.stages?.def||0)*.10)}) brightness(1.05)`:'';
let plate=e.querySelector('.metal-plating');const stage=park?Math.max(0,m.stages?.def||0):0;if(stage){if(!plate){plate=document.createElement('span');plate.className='metal-plating';e.append(plate);}plate.style.opacity=Math.min(.86,.24+stage*.12);}else plate?.remove();
let wealth=e.querySelector('.jackpot-wealth');if(!has(me,'choi','jackpot')||!coins[index]||m.fainted){wealth?.remove();continue;}const level=Math.min(3,coins[index]);if(!wealth){wealth=document.createElement('div');wealth.className='jackpot-wealth';wealth.setAttribute('aria-hidden','true');e.append(wealth);}if(Number(wealth.dataset.level)===level)continue;wealth.dataset.level=level;wealth.replaceChildren();for(let i=0;i<level*8;i++){const bit=document.createElement('span');bit.textContent=i%9===0?'💎':i%3?'💰':'🪙';bit.style.setProperty('--x',`${i*47%140-18}%`);bit.style.setProperty('--sz',`${12+level*3}px`);bit.style.setProperty('--dur',`${1.6+(i%5)*.32}s`);bit.style.setProperty('--delay',`${-(i%7)*.27}s`);bit.style.setProperty('--drift',`${(i%5-2)*16}px`);wealth.append(bit);}
}}
function canvasFX(kind,from,to){const f=document.getElementById('battle-screen');if(!f||!from||!to||matchMedia('(prefers-reduced-motion:reduce)').matches)return;let c=f.querySelector('.finisher-extra');if(!c){c=document.createElement('canvas');c.className='finisher-extra';f.append(c);}const id=++fxKey,w=f.clientWidth,h=f.clientHeight,d=Math.min(2,devicePixelRatio||1);c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');if(!ctx)return;ctx.setTransform(d,0,0,d,0,0);const a=at(from,f),b=at(to,f),start=performance.now(),length=kind==='stomp'?2450:1700;
if(kind==='stomp'){from.classList.add('stomp-leap');setTimeout(()=>from.classList.remove('stomp-leap'),length+50);}
function draw(now){if(id!==fxKey||!c.isConnected)return;const t=Math.min(1,(now-start)/length);ctx.clearRect(0,0,w,h);
if(kind==='wave'){const dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy),advance=dist*Math.min(1,t*1.2),rise=Math.min(205,h*.58);ctx.save();ctx.translate(a.x,a.y);ctx.rotate(Math.atan2(dy,dx));for(let layer=0;layer<4;layer++){const crest=rise*(1.2-layer*.18),x=advance-layer*14,g=ctx.createLinearGradient(0,-crest,0,crest*.65);g.addColorStop(0,['#02030a','#200b30','#7c2ca2','#d695f2'][layer]);g.addColorStop(1,'#07040ee6');ctx.fillStyle=g;ctx.globalAlpha=.7;ctx.shadowColor=layer?'#a73bea':'#000';ctx.shadowBlur=22;ctx.beginPath();ctx.moveTo(-35,crest*.7);ctx.bezierCurveTo(x*.2,-crest*.2,x*.63,-crest*1.04,x,-crest*.78);ctx.bezierCurveTo(x+crest*.28,-crest*.65,x+crest*.15,crest*.19,x-crest*.04,crest*.33);ctx.lineTo(-35,crest*.7);ctx.fill();}for(let i=0;i<34;i++){ctx.globalAlpha=.4;ctx.fillStyle=i%4?'#e9afff':'#0b0712';ctx.beginPath();ctx.arc(advance-(i%10)*12+Math.sin(i*2.4)*18,-rise*.7+Math.cos(i*3)*26,2+i%5,0,7);ctx.fill();}ctx.restore();}
else{const top=Math.max(18,b.y-h*.35),travel=ease(t/.26),jump=ease((t-.26)/.2),charge=ease((t-.46)/.18),back=ease((t-.76)/.24);let x=mix(a.x,b.x,travel),y=mix(a.y,top,travel),sz=46;if(t>.26&&t<=.46){x=b.x;y=top-54*Math.sin(Math.PI*jump);sz=46+18*jump;}if(t>.46&&t<=.76){x=b.x;y=top;sz=64+44*charge;}if(t>.76){x=mix(b.x,a.x,back);y=mix(top,a.y,back)-30*Math.sin(Math.PI*back);sz=108-62*back;}const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#060d20f0');sky.addColorStop(1,'#25344cd6');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.save();ctx.shadowColor='#f6be84';ctx.shadowBlur=22;if(front.complete&&front.naturalWidth)ctx.drawImage(front,x-sz/2,y-sz/2,sz,sz);else{ctx.fillStyle='#fff';ctx.font='900 19px system-ui';ctx.textAlign='center';ctx.fillText('박성원',x,y);}ctx.restore();if(t>.55&&t<.89){const reach=Math.max(0,(b.y-top-sz*.22)*ease((t-.55)/.19));for(const dir of [-1,1]){const legX=b.x+dir*28-11;ctx.save();ctx.fillStyle='#3b475a';ctx.shadowColor='#ff9d5a';ctx.shadowBlur=26;ctx.fillRect(legX,top+sz*.22,22,reach);ctx.fillStyle='#bac5d4';ctx.fillRect(legX-3,top+sz*.22+reach-10,28,12);ctx.restore();}}if(t>.74&&t<.89){ctx.save();ctx.translate(b.x,b.y);ctx.scale(1,.4);ctx.strokeStyle='#ffbc79';ctx.lineWidth=12;ctx.shadowColor='#ff8b3d';ctx.shadowBlur=25;ctx.beginPath();ctx.arc(0,0,w*.33*(t-.74)/.15,0,7);ctx.stroke();ctx.restore();}}
if(t<1)requestAnimationFrame(draw);else if(id===fxKey)c.remove();}requestAnimationFrame(draw);}
function sludgeHits(target){const f=document.getElementById('battle-screen');if(!f||!target)return;const p=at(target,f);for(let i=0;i<4;i++)setTimeout(()=>{if(!f.isConnected||!battleActive)return;const dot=document.createElement('span');dot.className='sludge-hit';dot.style.left=`${p.x+(i%2?17:-17)}px`;dot.style.top=`${p.y+(i%2?-12:12)}px`;f.append(dot);setTimeout(()=>dot.remove(),550);if(i&&typeof SFX?.hit==='function')SFX.hit();},i*130);}
function label(root,base,newName){if(!root)return;for(const el of root.querySelectorAll('b,span'))if(!el.childElementCount&&el.textContent?.includes(base))el.textContent=el.textContent.replaceAll(base,newName);}
function changeEvents(events){return events.map(ev=>{if(!ev?.msg)return ev;const side=ev.type==='move_announce'?ev.side:ev.actorSide;if(!side)return ev;let text=ev.msg;if(has(own(side),'park','meteor'))text=text.replaceAll('메테오 스트라이크','점프 내려찍기');if(has(own(side),'oh','abyss'))text=text.replaceAll('오물폭탄','오물웨이브');return text===ev.msg?ev:{...ev,msg:text};});}
function install(){
if(typeof window.renderBattleField==='function'){const old=window.renderBattleField;window.renderBattleField=function(...args){const result=old.apply(this,args);appearance();return result;};}
if(typeof window.startBattleScreen==='function'){const old=window.startBattleScreen;window.startBattleScreen=function(...args){fxKey++;token++;drain=stomp=sludge=null;flatTarget=null;flatUntil=-1;wobbleUntil=-1;coins.fill(0);leaders.fill(null);document.querySelector('.fractured-screen')?.remove();document.querySelector('.finisher-extra')?.remove();for(const el of [sprite(true),sprite(false)])el?.classList.remove('stomp-leap','stomp-squashed');const result=old.apply(this,args);appearance();return result;};}
if(typeof window.openMoveMenu==='function'){const old=window.openMoveMenu;window.openMoveMenu=function(...args){const result=old.apply(this,args);for(let i=0;i<4;i++){const e=document.getElementById(`m${i}-name`);if(has(true,'park','meteor')&&e?.textContent==='메테오 스트라이크')e.textContent='점프 내려찍기';if(has(true,'oh','abyss')&&e?.textContent==='오물폭탄')e.textContent='오물웨이브';}return result;};}
if(typeof window.showCharDetail==='function'){const old=window.showCharDetail;window.showCharDetail=function(id,...args){const result=old.call(this,id,...args);if(id==='park'&&saved('park','meteor'))label(document.getElementById('d-moves'),'메테오 스트라이크','점프 내려찍기');if(id==='oh'&&saved('oh','abyss'))label(document.getElementById('d-moves'),'오물폭탄','오물웨이브');return result;};}
if(typeof window.renderDetailModalContent==='function'){const old=window.renderDetailModalContent;window.renderDetailModalContent=function(...args){const result=old.apply(this,args),sections=document.querySelectorAll('#modal-body-content .status-columns > div');for(const me of [true,false]){const root=sections[me?0:1];if(has(me,'park','meteor'))label(root,'메테오 스트라이크','점프 내려찍기');if(has(me,'oh','abyss'))label(root,'오물폭탄','오물웨이브');}return result;};}
if(typeof window.playTurnEvents==='function'){const old=window.playTurnEvents;window.playTurnEvents=function(events){const result=old.call(this,Array.isArray(events)?changeEvents(events):events);return result?.finally?result.finally(appearance):result;};}
if(typeof window.triggerSkillVisualAndAudio==='function'){const old=window.triggerSkillVisualAndAudio;window.triggerSkillVisualAndAudio=function(name,side,...args){const me=own(side),park=name==='메테오 스트라이크'&&has(me,'park','meteor'),oh=name==='오물폭탄'&&has(me,'oh','abyss'),f=document.getElementById('battle-screen'),ticket=++token;if(f)f.dataset.parkStomp=park?'yes':'off';const base=window.playSkillCinematicFX;if(park&&typeof base==='function')window.playSkillCinematicFX=function(n,...rest){if(n==='메테오 스트라이크')return;return base.call(this,n,...rest);};let result;try{result=old.call(this,name,side,...args);}finally{if(park&&typeof base==='function')window.playSkillCinematicFX=base;}if(name==='드레인펀치'&&has(me,'bae','bloodmoon'))drain={at:Date.now(),target:sprite(!me)};if(oh){sludge={at:Date.now(),target:sprite(!me)};canvasFX('wave',sprite(me),sprite(!me));}if(park){stomp={at:Date.now(),target:sprite(!me),id:mon(!me)?.id};canvasFX('stomp',sprite(me),sprite(!me));setTimeout(()=>{if(ticket===token&&f)f.dataset.parkStomp='off';},3400);}if(name==='수능 가챠'&&args[1]?.isGachaWin&&has(me,'choi','jackpot')){coins[me?0:1]++;appearance();}return result;};}
if(typeof window.playSkillCinematicImpactFX==='function'){const old=window.playSkillCinematicImpactFX;window.playSkillCinematicImpactFX=function(name,point){if(name==='메테오 스트라이크'&&stomp&&Date.now()-stomp.at<8000){flatTarget=stomp.target;flatId=stomp.id;flatBattle=battleGeneration;flatUntil=currentTurnNumber+1;const f=document.getElementById('battle-screen');if(f)f.dataset.parkStomp='impact';shake();appearance();stomp=null;return;}const result=old.call(this,name,point);if(name==='드레인펀치'&&drain&&Date.now()-drain.at<8000){shake();cracks(drain.target);drain=null;}if(name==='오물폭탄'&&sludge&&Date.now()-sludge.at<8000){wobbleBattle=battleGeneration;wobbleUntil=currentTurnNumber+1;sludgeHits(sludge.target);appearance();sludge=null;}return result;};}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
