// Skin gallery, code redemption, random arenas, and local dummy FX lab.
(() => {
'use strict';
const KEY='ochams-skins-v1';
const SKINS=[{id:'storm',owner:'lee',name:'적뢰',image:'lee-red.png',back:'lee-red-back.png',icon:'⚡',color:'#f43f5e'},{id:'bloodmoon',owner:'bae',name:'혈월의 권투사',image:'bae-bloodmoon.png',back:'bae-bloodmoon-back.png',icon:'✊',color:'#ef4444'},{id:'abyss',owner:'oh',name:'심연의 독술사',image:'oh-abyss.png',back:'oh-abyss-back.png',icon:'☠',color:'#a855f7'},{id:'meteor',owner:'park',name:'흑철 운석',image:'park-meteor.jpg',back:'park-meteor-back.jpg',icon:'☄',color:'#fb923c'},{id:'jackpot',owner:'choi',name:'청염 도박사',image:'choi-jackpot.png',back:'choi-jackpot-back.png',icon:'🎰',color:'#38bdf8'},{id:'rift',owner:'yoon',name:'균열의 마녀',image:null,icon:'✦',color:'#e879f9'},{id:'jester',owner:'boingo',name:'심야의 광대',image:null,icon:'♠',color:'#f9a8d4'},{id:'rewind',owner:'sungwon_time',name:'역행',image:null,icon:'⌛',color:'#67e8f9'}];
const ARENAS=[{id:'neon',name:'네온 거리'},{id:'volcano',name:'화산 지대'},{id:'moon',name:'달빛 폐허'},{id:'storm',name:'뇌운 사원'}];
function read(){try{const d=JSON.parse(localStorage.getItem(KEY)||'{}');return d&&typeof d==='object'?d:{};}catch(e){console.warn('스킨 저장 정보 오류',e);return {};}}
function write(d){try{localStorage.setItem(KEY,JSON.stringify(d));return true;}catch(e){console.warn('스킨 저장 실패',e);return false;}}
const style=document.createElement('style');style.textContent=`
.skin-gallery{position:fixed;inset:0;z-index:260;background:rgba(3,7,18,.88);display:flex;align-items:center;justify-content:center;padding:14px}
.skin-gallery-card{width:min(580px,100%);max-height:90vh;overflow-y:auto;background:#152238;border:2px solid #7dd3fc;border-radius:15px;padding:14px;color:#f8fafc;box-shadow:0 18px 60px #000c}
.skin-gallery-card h2{font-size:18px;margin:0 0 6px;color:#a5f3fc}.skin-gallery-card p{font-size:12px;color:#cbd5e1;line-height:1.5;margin:0 0 10px}
.skin-gallery-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
.skin-gallery-item{display:flex;gap:9px;align-items:center;padding:8px;border-radius:9px;background:#21324b;border:1px solid #516981;min-width:0}.skin-gallery-item.locked{background:#1a2638}
.skin-gallery-preview{width:70px;height:70px;flex:none;display:grid;place-items:center;overflow:hidden;border:2px solid var(--skin-color);border-radius:10px;background:radial-gradient(circle at center,var(--skin-color),#101421 75%);font-size:28px;text-shadow:0 2px 9px #000}
.skin-gallery-preview img{width:100%;height:100%;object-fit:contain;display:block}.skin-gallery-meta{min-width:0;flex:1}.skin-gallery-name{font-size:12px;font-weight:900;overflow-wrap:anywhere}.skin-gallery-owner{font-size:10px;color:#a5f3fc;margin:3px 0}.skin-gallery-status{font-size:10px;color:#cbd5e1}
.skin-gallery-item button{margin-top:4px;min-height:29px;width:100%;font-size:11px;background:#2563eb}.skin-gallery-close{width:100%;margin-top:10px;background:#475569}
.skin-code-btn{width:100%;margin:8px 0;min-height:38px;background:#7c3aed!important;color:#fff}
.skin-code-row{display:flex;gap:8px;margin:8px 0}.skin-code-row input{min-width:0;flex:1;background:#0f172a;color:white;border:1px solid #7dd3fc;border-radius:7px;padding:9px}.skin-code-row button{background:#7c3aed;color:#fff;padding:8px 12px;border-radius:7px}
.skin-code-status{min-height:20px;color:#fda4af!important}
.lab-launch{display:block;width:min(320px,100%);margin:9px auto;padding:10px;background:#0e7490;color:white;border:1px solid #67e8f9;border-radius:9px;font-weight:800}
.lab-controls{position:fixed;bottom:8px;left:50%;transform:translateX(-50%);z-index:290;width:min(780px,calc(100% - 16px));padding:10px;background:#111d36f5;color:white;border:1px solid #7dd3fc;border-radius:11px;box-shadow:0 8px 30px #000a;display:flex;flex-wrap:wrap;gap:7px;align-items:center;justify-content:center;font:12px system-ui}
.lab-controls select,.lab-controls button,.lab-config select,.lab-config button{background:#263a58;color:#fff;border:1px solid #64748b;border-radius:7px;padding:7px;min-height:35px}.lab-controls button{background:#0369a1}.lab-controls .lab-exit{background:#9f1239}.lab-controls .lab-status{flex-basis:100%;text-align:center;color:#a5f3fc}
.lab-config{display:grid;gap:9px}.lab-config label{display:grid;gap:4px;font-size:12px}.lab-config p{margin:0}
@media(max-width:480px){.skin-gallery-grid{grid-template-columns:1fr}.skin-gallery-preview{width:62px;height:62px}.lab-controls{bottom:2px}}
#battle-screen[data-arena="neon"]{background:radial-gradient(circle at 48% 25%,#fb4bc355,transparent 39%),repeating-linear-gradient(0deg,transparent 0 26px,#32d6fc15 27px 28px),linear-gradient(130deg,#030b29,#38125a 52%,#061a3b)}
#battle-screen[data-arena="neon"]::before{background:repeating-linear-gradient(90deg,transparent 0 34px,#ff53e31e 35px 37px),linear-gradient(0deg,#14b8a635,transparent 60%)}
#battle-screen[data-arena="volcano"]{background:radial-gradient(ellipse at 74% 85%,#ff7a22aa,transparent 42%),radial-gradient(circle at 48% 10%,#72231b88,transparent 40%),linear-gradient(#180b17,#3b1725 70%,#261017)}
#battle-screen[data-arena="volcano"]::before{background:repeating-linear-gradient(14deg,transparent 0 30px,#ff842215 32px 35px),linear-gradient(0deg,#f851194d,transparent 43%)}
#battle-screen[data-arena="moon"]{background:radial-gradient(circle at 72% 23%,#dbeafe9c 0 7%,#92a7ed44 10%,transparent 26%),linear-gradient(135deg,#060f28,#25345c 60%,#0a1a31)}
#battle-screen[data-arena="moon"]::before{background:repeating-linear-gradient(95deg,transparent 0 49px,#dbeafe19 51px 54px),linear-gradient(0deg,#b3c6ff37,transparent 48%)}
#battle-screen[data-arena="storm"]{background:radial-gradient(circle at 48% 18%,#dbfaff42,transparent 32%),repeating-linear-gradient(120deg,transparent 0 65px,#cceefa18 68px 71px),linear-gradient(145deg,#071622,#234252 50%,#101529)}
#battle-screen[data-arena="storm"]::before{background:radial-gradient(ellipse at 50% 80%,#9c70e743,transparent 65%),linear-gradient(90deg,transparent 46%,#a5f3fc29 49%,transparent 51%)}
.arena-title{position:absolute;top:49%;left:50%;transform:translate(-50%,-50%);z-index:11;pointer-events:none;padding:5px 11px;background:#080f22c9;border:1px solid #cbd5e1;border-radius:7px;color:#fff;font:900 13px system-ui;white-space:nowrap;animation:arenaTitle 1.7s ease-out both}
@keyframes arenaTitle{0%{opacity:0;transform:translate(-50%,-40%) scale(.9)}20%,65%{opacity:1;transform:translate(-50%,-50%) scale(1)}100%{opacity:0}}
@media(prefers-reduced-motion:reduce){.arena-title{animation:none;opacity:1}}
`;document.head.append(style);
function modal(titleText){const shade=document.createElement('div');shade.className='skin-gallery';shade.setAttribute('role','dialog');shade.setAttribute('aria-modal','true');const card=document.createElement('div');card.className='skin-gallery-card';const title=document.createElement('h2');title.textContent=titleText;card.append(title);shade.append(card);document.body.append(shade);const close=document.createElement('button');close.type='button';close.className='skin-gallery-close';close.textContent='닫기';close.onclick=()=>shade.remove();return{shade,card,close};}
function codeDialog(){document.querySelector('.skin-gallery')?.remove();const{card,close}=modal('🎟️ 스킨 코드 입력');const intro=document.createElement('p');intro.textContent='코드를 입력하면 해당 스킨이 이 브라우저의 보관함에 지급됩니다.';const row=document.createElement('div');row.className='skin-code-row';const input=document.createElement('input');input.type='text';input.placeholder='코드 입력';input.autocomplete='off';input.setAttribute('aria-label','스킨 코드');const submit=document.createElement('button');submit.type='button';submit.textContent='확인';const status=document.createElement('p');status.className='skin-code-status';status.setAttribute('role','status');const redeem=()=>{if(input.value.trim().toLowerCase()!=='ddalbae'){status.textContent='유효하지 않은 코드입니다.';return;}const data=read(),owned=new Set(Array.isArray(data.unlocked)?data.unlocked:[]);if(owned.has('bloodmoon')){status.textContent='이미 혈월 스킨을 보유하고 있습니다.';return;}owned.add('bloodmoon');data.unlocked=[...owned];if(write(data)){status.textContent='혈월의 권투사 해금! 보관함에서 장착할 수 있습니다.';input.disabled=true;submit.disabled=true;setTimeout(()=>location.reload(),850);}else status.textContent='저장할 수 없습니다. 브라우저 저장 설정을 확인해 주세요.';};submit.onclick=redeem;input.onkeydown=e=>{if(e.key==='Enter')redeem();};row.append(input,submit);card.append(intro,row,status,close);input.focus();}
function labelFor(owner){return typeof POKEDEX!=='undefined'?(POKEDEX[owner]?.name||owner):owner;}
function openGallery(unlockMode=false){document.querySelector('.skin-gallery')?.remove();const data=read(),owned=new Set(Array.isArray(data.unlocked)?data.unlocked:[]),available=SKINS.filter(s=>!owned.has(s.id));const{card,close}=modal(unlockMode?'🛠️ 개발자 스킨 선택':'🎨 전체 스킨 도감');const intro=document.createElement('p');intro.textContent=unlockMode?(available.length?'미해금 스킨 중 하나를 선택해 즉시 해금·장착합니다.':'모든 스킨을 해금했습니다.'):'8명 전용 스킨 미리보기 · 혈월은 코드로, 다른 스킨은 3연전 승리 또는 개발자 기능으로 해금';card.append(intro);const grid=document.createElement('div');grid.className='skin-gallery-grid';for(const skin of SKINS){const item=document.createElement('div');item.className='skin-gallery-item';item.style.setProperty('--skin-color',skin.color);const unlocked=owned.has(skin.id);if(!unlocked)item.classList.add('locked');const preview=document.createElement('div');preview.className='skin-gallery-preview';preview.setAttribute('aria-label',`${skin.name} 미리보기`);if(skin.image){const img=document.createElement('img');img.alt=`${skin.name} 앞모습`;img.loading='lazy';img.src=`assets/skins/${skin.image}`;img.onerror=()=>{img.remove();preview.textContent=skin.icon;};preview.append(img);}else preview.textContent=skin.icon;const meta=document.createElement('div');meta.className='skin-gallery-meta';const name=document.createElement('div');name.className='skin-gallery-name';name.textContent=skin.name;const owner=document.createElement('div');owner.className='skin-gallery-owner';owner.textContent=labelFor(skin.owner);const status=document.createElement('div');status.className='skin-gallery-status';const currently=data.equipped?.[skin.owner]===skin.id;status.textContent=unlocked?(currently?'장착 중':'해금됨'):(skin.image?'미해금':'미해금 · 전용 사진 없음');meta.append(name,owner,status);if(unlockMode&&!unlocked){const btn=document.createElement('button');btn.type='button';btn.textContent='해금하기';btn.onclick=()=>{const d=read(),list=Array.isArray(d.unlocked)?d.unlocked.filter(id=>SKINS.some(s=>s.id===id)):[];if(!list.includes(skin.id))list.push(skin.id);d.unlocked=list;d.equipped={...(d.equipped||{}),[skin.owner]:skin.id};d.claimed=true;if(write(d))location.reload();};meta.append(btn);}else if(!unlockMode&&unlocked){const btn=document.createElement('button');btn.type='button';btn.textContent=currently?'장착 해제':'장착하기';btn.onclick=()=>{const d=read();d.equipped={...(d.equipped||{})};if(currently)delete d.equipped[skin.owner];else d.equipped[skin.owner]=skin.id;if(write(d))location.reload();};meta.append(btn);}item.append(preview,meta);grid.append(item);}card.append(grid,close);}
const picks=document.getElementById('pick-panel');if(picks&&!document.getElementById('skin-code-btn')){const button=document.createElement('button');button.id='skin-code-btn';button.type='button';button.className='skin-code-btn';button.textContent='🎟️ 코드 입력';button.onclick=codeDialog;const wardrobe=picks.querySelector('.skin-entry-btn');if(wardrobe)wardrobe.insertAdjacentElement('afterend',button);else picks.append(button);}
const wardrobe=document.querySelector('#pick-panel .skin-entry-btn');if(wardrobe)wardrobe.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openGallery();},true);
let clicks=0;const detail=document.getElementById('btn-show-info');if(detail)detail.addEventListener('click',e=>{if(++clicks<12)return;clicks=0;e.preventDefault();e.stopImmediatePropagation();const old=document.getElementById('detail-modal');if(old)old.style.display='none';openGallery(true);},true);
if(typeof window.startBattleScreen==='function'){const old=window.startBattleScreen;window.startBattleScreen=function(...args){const result=old.apply(this,args),field=document.getElementById('battle-screen');if(field){const arena=ARENAS[Math.floor(Math.random()*ARENAS.length)];field.dataset.arena=arena.id;field.querySelector('.arena-title')?.remove();const title=document.createElement('div');title.className='arena-title';title.textContent=arena.name;title.setAttribute('aria-hidden','true');field.append(title);setTimeout(()=>title.remove(),1800);}return result;};}
let lab=null;
function dummy(){const m=buildMon('park');m.id='dummy';m.name='허수아비';m.ability='없음';m.abilityDesc='연출 테스트용';m.hp=m.maxHp=9999;m.stages={atk:0,def:0,spa:0,spd:0,spe:0};return m;}
function team(lead){return{lead,bench:[buildMon('yoon'),buildMon('lee')]};}
function syncLab(){if(!lab)return;const actorSprite=document.getElementById(lab.view==='mine'?'player-sprite':'enemy-sprite'),dummySprite=document.getElementById(lab.view==='mine'?'enemy-sprite':'player-sprite');if(!actorSprite||!dummySprite)return;const skin=SKINS.find(s=>s.id===lab.skin);if(skin){actorSprite.dataset.skin=skin.id;actorSprite.style.setProperty('--skin-glow',skin.color);}else{delete actorSprite.dataset.skin;actorSprite.style.removeProperty('--skin-glow');}const img=actorSprite.querySelector('img.champion-art');if(img){const local=lab.view==='mine',file=skin?.image?(local?skin.back:skin.image):`${lab.actor}${local?'-back':''}.png`;const src=skin?.image?`assets/skins/${file}`:`assets/sprites/${file}`;if(img.getAttribute('src')!==src)img.src=src;}delete dummySprite.dataset.skin;dummySprite.querySelector('img.champion-art')?.remove();const name=dummySprite.querySelector('.sprite-label');if(name)name.textContent='허수아비';}
function addOption(select,value,text){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}
function closeLab(){if(!lab||lab.busy)return;lab.panel?.remove();lab=null;restartToLobby();}
function startLab(actor,skin,view){if(lab||!Object.prototype.hasOwnProperty.call(POKEDEX,actor))return;const d=read(),allowed=SKINS.find(s=>s.id===skin&&s.owner===actor&&d.unlocked?.includes(s.id)&&d.equipped?.[actor]===s.id);lab={actor,skin:allowed?skin:'',view,busy:false,panel:null};startAiMode();isHost=view==='mine';isAiMode=true;isSpectator=false;const fighter=buildMon(actor),target=dummy();myTeam=team(view==='mine'?fighter:target);enemyTeam=team(view==='mine'?target:fighter);startBattleScreen();const cmd=document.getElementById('section-cmd');if(cmd)cmd.style.display='none';syncLab();lab.panel=labPanel();}
function labPanel(){const panel=document.createElement('div');panel.className='lab-controls';panel.setAttribute('role','group');panel.setAttribute('aria-label','전투 연출 테스트룸');const move=document.createElement('select');move.setAttribute('aria-label','테스트할 기술');for(const m of POKEDEX[lab.actor].moves){const renamed=lab.skin==='meteor'&&m.name==='메테오 스트라이크'?'점프 내려찍기':lab.skin==='abyss'&&m.name==='오물폭탄'?'오물웨이브':m.name;addOption(move,m.name,renamed);}if(lab.actor==='lee')addOption(move,'벽력일섬','벽력일섬 (니카)');const outcome=document.createElement('select');outcome.setAttribute('aria-label','테스트 판정');for(const [v,t] of [['hit','명중'],['miss','빗나감'],['protect','방어']])addOption(outcome,v,t);const view=document.createElement('button');view.type='button';view.textContent=lab.view==='mine'?'내 시점 → 상대 시점':'상대 시점 → 내 시점';view.onclick=()=>{if(lab.busy)return;const a=lab.actor,s=lab.skin,v=lab.view==='mine'?'enemy':'mine';closeLab();startLab(a,s,v);};const play=document.createElement('button');play.type='button';play.textContent='▶ 연출 재생';const leave=document.createElement('button');leave.type='button';leave.className='lab-exit';leave.textContent='테스트 종료';leave.onclick=closeLab;const status=document.createElement('div');status.className='lab-status';status.setAttribute('role','status');status.textContent='허수아비 상대 · 장착한 스킨 기준 · 결과는 저장되지 않음';play.onclick=async()=>{if(!lab||lab.busy||isProcessingTurn)return;const selected=POKEDEX[lab.actor].moves.find(m=>m.name===move.value)||(lab.actor==='lee'&&move.value==='벽력일섬'?{name:'벽력일섬',role:'공격'}:null);if(!selected)return;lab.busy=true;play.disabled=true;view.disabled=true;status.textContent=`${move.selectedOptions[0].textContent} · ${outcome.selectedOptions[0].textContent} 재생 중`;try{syncLab();const name=selected.name,events=[{type:'move_announce',side:'p1',targetSide:'p2',moveName:name,msg:`${POKEDEX[lab.actor].name}의 ${name}!`}];if(outcome.value==='hit'&&selected.role==='공격')events.push({type:'damage',targetSide:'p2',actorSide:'p1',actorName:POKEDEX[lab.actor].name,targetName:'허수아비',moveName:name,dmg:32,targetHp:9999,targetMaxHp:9999,isCrit:false,effectiveness:1,msg:'허수아비에게 32 피해!'});else if(outcome.value==='miss')events.push({type:'msg',msg:'그러나 공격은 빗나갔다!'});else if(outcome.value==='protect')events.push({type:'protect',side:'p2',msg:'허수아비가 공격을 막아냈다!'});await playTurnEvents(events);status.textContent='재생 완료 · 기술과 판정을 바꿔 다시 볼 수 있습니다.';}catch(e){console.error('테스트룸 재생 오류',e);status.textContent='재생 오류가 발생했습니다. 콘솔을 확인해 주세요.';}finally{if(lab){lab.busy=false;play.disabled=false;view.disabled=false;syncLab();}}};panel.append(move,outcome,view,play,leave,status);document.body.append(panel);return panel;}
function labDialog(){document.querySelector('.skin-gallery')?.remove();const{card,close,shade}=modal('🧪 전투 연출 테스트룸');const form=document.createElement('div');form.className='lab-config';const text=document.createElement('p');text.textContent='허수아비를 상대로 실제 기술 이벤트를 재생합니다. 스킨은 현재 장착 상태를 사용하며 온라인 상대와 연결하지 않습니다.';const actor=document.createElement('select');for(const [id,p] of Object.entries(POKEDEX))addOption(actor,id,p.name);const skin=document.createElement('select');const refresh=()=>{skin.replaceChildren();const d=read(),equipped=SKINS.find(s=>s.owner===actor.value&&d.unlocked?.includes(s.id)&&d.equipped?.[actor.value]===s.id);if(equipped)addOption(skin,equipped.id,`${equipped.name} (장착 중)`);else addOption(skin,'','기본 외형');};actor.onchange=refresh;refresh();const view=document.createElement('select');addOption(view,'mine','내 시점');addOption(view,'enemy','상대 시점');const label=(title,input)=>{const row=document.createElement('label');row.textContent=title;row.append(input);return row;};const start=document.createElement('button');start.type='button';start.textContent='허수아비 테스트 시작';start.onclick=()=>{const a=actor.value,s=skin.value,v=view.value;shade.remove();startLab(a,s,v);};form.append(text,label('시전자',actor),label('스킨 (장착 상태)',skin),label('시점',view),start,close);card.append(form);}
const lobby=document.getElementById('lobby-panel');if(lobby&&!document.getElementById('lab-launch')){const button=document.createElement('button');button.type='button';button.id='lab-launch';button.className='lab-launch';button.textContent='🧪 전투 연출 테스트룸';button.onclick=labDialog;lobby.append(button);}
const installLabRender=()=>{if(typeof window.renderBattleField!=='function')return;const old=window.renderBattleField;window.renderBattleField=function(...args){const result=old.apply(this,args);syncLab();return result;};};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installLabRender,{once:true});else installLabRender();
})();
